### ISSUE TITLE
Selected Value

### ISSUE THREAD

**Issue by t3mh4** [sergiodlopes/jquery-flexdatalist#15]
Hii,
how can i get selected value empty if there is no match?

**Comment by sergiodlopes** [comment]
Hi,

Not sure if I understood your question. Is that a bug? Can you post what you're trying to do?

**Comment by t3mh4** [comment]
Hi,
whem i select Taiwan it gives its value.then i wrote random word like "abc" it still gives me Taiwans value.

**Comment by sergiodlopes** [comment]
Hi,

Oh, I see. I think that bug was fixed on release 1.7.3. Can you confirm on the [documentation page](http://projects.sergiodinislopes.pt/flexdatalist/) if that's the case?

Thanks!

**Comment by t3mh4** [comment]
hii,
no it was not fixed. i have tried on the  [documentation page](http://projects.sergiodinislopes.pt/flexdatalist/) many times.

**Comment by sergiodlopes** [comment]
When did you tried it?

**Comment by t3mh4** [comment]
ok it was fixed :)

**Comment by sergiodlopes** [comment]
Oh, great! :)

Thanks!

**Comment by t3mh4** [comment]
sorry but it was not working.
first i select Taiwan i get value.then if i clear text the value becomes empty.
but i select Taiwan text with double click then i type "abc" it still show Taiwans' value..
i tried this in selectionRequired example

**Comment by sergiodlopes** [comment]
I'm sorry, but I can't replicate the bug. What browser you're using?

**Comment by t3mh4** [comment]
Chrome 54.0.2840.71

**Comment by sergiodlopes** [comment]
Oh, I found it! sorry, I wasn't looking at the value. Good catch... :D Hehe.

**Comment by sergiodlopes** [comment]
It should be fixed on 1.7.4. Please, test if it is the case now.
Thanks!

**Comment by t3mh4** [comment]
its ok now thanks alot:)

**Comment by sergiodlopes** [comment]
Thanks for bringing it up.

**Comment by akovacsapeter** [comment]
Hello!
I like this plugin a lot, but there is a problem. If the json has an id / value pair, and I give the value to the field, it gets label (value) by like. For example, I have a JSON like this:
[{"id":"3","name":"Bulgarian"},{"id":"11","name":"Croatian"},{"id":"4","name":"Czech"},{"id":"5","name":"Danish"},{"id":"10","name":"Dutch"},{"id":"1","name":"English"},{"id":"6","name":"Estonian"},{"id":"7","name":"Finnish"},{"id":"8","name":"French"},{"id":"13","name":"German"},{"id":"9","name":"Greek"},{"id":"2","name":"Hungarian"},{"id":"12","name":"Irish"},{"id":"14","name":"Italian"},{"id":"16","name":"Latvian"},{"id":"17","name":"Lithuanian"},{"id":"18","name":"Maltese"},{"id":"15","name":"Polish"},{"id":"19","name":"Portuguese"},{"id":"20","name":"Romanian"},{"id":"23","name":"Slovak"},{"id":"24","name":"Slovene"},{"id":"21","name":"Spanish"},{"id":"22","name":"Swedish"}]
and I give "2" as value to the field, it shows an element LIKE '%2%' not = '2'.
In this example I gave to the field "2" and it shows "Sweden" instead of "Hungary".
If i give "1" it shows "Portugese" instead "English".
But if I give for example "12", it shows correctly "Irish" - as a result of a LIKE operation (looks like).
What can I do whit that please?

**Comment by sergiodlopes** [comment]
Hi,

I'm without time to place a demo for this, at the moment. Could you please set up a simple demo with the problem?

Thanks!

**Comment by akovacsapeter** [comment]
Of course, I create one. Thanks!

**Comment by sergiodlopes** [comment]
I see the problem. Thanks.

Can you please try with v1.9.3 and see if solves the issue?

**Comment by akovacsapeter** [comment]
Thanks Sérgio, I try and inform you.

 

Peter

**Comment by akovacsapeter** [comment]
Hello Sérgio,

 

Unfortunately the same with v1.9.3

 

Kind regards

Peter

**Comment by sergiodlopes** [comment]
OK. I'll check it out later today.

Thanks for the heads up about the problem/bug.

**Comment by akovacsapeter** [comment]
Hello Sergio,
Unfortunatelly the same problem with 1.9.4. What do you think, will it be fixed in the near future?
Thanks, Peter
